name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
        NODE_ENV: "development"
        PORT: 3000
        MONGO_URL: "mongodb://localhost:27017/books"
        SECRET_HEX: "827d263847500d926a520be9c69137906dcc05df5a326ea2262f52d4f9db37b9"
        ACCESS_TOKEN_LIFETIME_MIN: 60
        BCRYPT_N_ROUNDS: 10
        WHITELIST_ORIGINS: ["http://localhost"]
        SMTP_USER: "project"
        SMTP_PASS: "secret"
        SMTP_PORT: 1025
        SMTP_HOST: "localhost"
        SMTP_FROM_EMAIL: "no-reply@example.com":  
